spring.application.name=family-information-system

spring.datasource.url=jdbc:mysql://mysql-1b8170bc-mdsanaullah129-3a8a.f.aivencloud.com:16923/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}